Host: "127.0.0.1"
Internal_Port: "8078"
#Database_Connection: "$PRODDBCONN"
Database_Connection: "assets/murdock.db"
#Worker_Token: "$WORKERTOKEN"
#Worker_Hash: "$WORKERHASH"
Worker_Token: "0c68feae3aa59d3d3d7ebe892e077d98f82108b7c38af3d2c6d50b44572f4c77"
Worker_Hash: "$2a$10$eZOYmxRUU9a.1rjfzUybe.jbLVua6sWl/RxeFvv54gbAVS0Ue//Q2"
Admin_Token: "$ADMINTOKEN"
Admin_Hash: "$ADMINHASH"
